language: go

go:
  - 1.11.6
  
branches:
  only:
    - master

before_install:
- ./look_for_logs.sh
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get github.com/golang/lint/golint
- go get github.com/GeertJohan/fgt
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover;
  fi
  
script:
- fgt golint $(find client | grep .go$ | grep -v server.pb.go | grep -v test.pb.go)
- fgt golint keystoreapi.go store.go
- go test ./...
- $HOME/gopath/bin/goveralls -service=travis-ci -ignore keystore.go,keystoreapi.go -package github.com/brotherlogic/keystore/
#- $HOME/gopath/bin/goveralls -service=travis-ci -ignore client/keystoreclientapi.go -package github.com/brotherlogic/keystore/client