language: go

go:
  - 1.7
  
branches:
  only:
    - master

before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get github.com/golang/lint/golint
- go get github.com/GeertJohan/fgt
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover;
  fi
  
script:
- fgt golint $(find . | grep .go$ | grep -v test.pb.go)
- go test ./...
- $HOME/gopath/bin/goveralls -service=travis-ci -ignore keystoreapi.go -package github.com/brotherlogic/keystore