// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package testproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestProto struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestProto) Reset()         { *m = TestProto{} }
func (m *TestProto) String() string { return proto.CompactTextString(m) }
func (*TestProto) ProtoMessage()    {}
func (*TestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *TestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestProto.Unmarshal(m, b)
}
func (m *TestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestProto.Marshal(b, m, deterministic)
}
func (m *TestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestProto.Merge(m, src)
}
func (m *TestProto) XXX_Size() int {
	return xxx_messageInfo_TestProto.Size(m)
}
func (m *TestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TestProto.DiscardUnknown(m)
}

var xxx_messageInfo_TestProto proto.InternalMessageInfo

func (m *TestProto) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TestProto) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*TestProto)(nil), "testproto.TestProto")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xb1, 0xc1, 0x4c, 0x25, 0x63, 0x2e, 0xce,
	0x90, 0xd4, 0xe2, 0x92, 0x00, 0xb0, 0xb8, 0x00, 0x17, 0x73, 0x76, 0x6a, 0xa5, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x88, 0x29, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x2a, 0xc1,
	0x04, 0x16, 0x83, 0x70, 0x92, 0xd8, 0xc0, 0x7a, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x36,
	0x83, 0x38, 0x81, 0x54, 0x00, 0x00, 0x00,
}
